version: "3"

services:
  database:
    container_name: sql-database
    build: ./database/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root-psw
      MYSQL_USER: "client"
      MYSQL_PASSWORD: "client-psw"
    restart: always
    tty: true

  admin:
    container_name: admin
    build: ./admin/
    ports:
      - 3000:3000
    volumes:
      - ./admin:/admin
    command: npm run dev
    depends_on:
      - database
    tty: true
    restart: always

  shop:
    container_name: shop
    build: ./shop/
    ports:
      - 3001:3001
    volumes:
      - ./shop:/shop
    command: npm run dev
    depends_on:
      - database
    tty: true
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 3002:80
    environment:
      PMA_HOST: database
    depends_on:
      - database
